spring:
  application:
    name: spring-ai-rag-expert
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      embedding:
        options:
          model: gpt-4
sfg:
  aiapp:
    apiNinjasKey:  ${API_NINJAS_KEY}